language: python
python: 3.6

install: pip install -r requirements_dev.txt
script: pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mpicard
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: mpicard/python_eureka_client
    python: 3.6
